name: Push Tokens
on: 
  push:
    branches:
      - main
    paths:
      - 'build/**'

jobs:
  deploy:
    name: Push Tokens
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '/build/web/'
          target-directory: '/src/variables/'
          destination-github-username: 'ethanWallace'
          destination-repository-name: 'gc-ds-core'
          user-email: ethan.wallace.91@gmail.com
          target-branch: main